name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build, Test and Coverage
      run: ./mvnw -B clean verify

    - name: Codecov Code Coverage
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true # optional (default = false)
        files: ./target/site/jacoco/jacoco.xml
        flags: unittests # optional
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: false

    - name: Run Rewrite Dry Run
      run: ./mvnw -B rewrite:dryRun -DfailOnDryRunResults=true

